### ISSUE TITLE
error when set ftpd.Conf.set_max_concurrent_jobs

### ISSUE THREAD

**Issue by peiliu0408** [VFLins/ftp_download#1]
as mention in title,
<img width="777" alt="截屏2024-03-13 11 38 03" src="https://github.com/VFLins/ftp_download/assets/18061950/7269cc6b-ed50-4842-8093-0cdb98cd8797">
can you help me with this?

**Comment by VFLins** [comment]
Sorry about that, i implemented `set_max_concurrent_jobs` as a way of limiting the amount of concurrent downloads, so you don't overflow your internet bandwidth.

But later on I discovered that whether you request __concurrently__ (ask all files at once) or __sequentially__ (wait for a download to finish to ask for another file) will not matter. FTP servers will always send one file at a time, so it seems that this feature isn't necessary and is now removed from the code base, but I forgot to take it out from the README.

You can still enable __concurrent__ requests by using `ftpd.Conf.use_async = True`, it will only be useful if you want your code to send the download requests and then proceed to an unrelated task that don't require the downloads to finish.

Please let me know if you need any additional help.

**Comment by VFLins** [comment]
Closing the issue for inactivity, feel free to open another one if you have another question.
